# Generated by Django 2.1.4 on 2019-01-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_shortdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shortdescription',
            name='text',
            field=models.TextField(max_length=300),
        ),
    ]
