# Generated by Django 2.1.4 on 2019-01-14 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_portfoliocatalog_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliocatalog',
            name='data',
            field=models.DateField(default=datetime.date(2019, 1, 14)),
        ),
    ]
