# Generated by Django 2.1.4 on 2019-01-15 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20190114_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliocatalog',
            name='data',
            field=models.DateField(default=datetime.date(2019, 1, 15)),
        ),
    ]
